main: main.o Logger.o IObservable.o Characters.o Player.o Item.o Heal.o Box.o Teleport.o fightView.o 
HitMonsterPrint.o MissMonsterPrint.o Enemy.o Smonster.o Mmonster.o Lmonster.o Cellule.o 
CelluleView.o Field.o FieldView.o ExitDoorPrint.o Game.o
	g++ main.o Logger.o IObservable.o Characters.o Player.o Item.o Heal.o Box.o Teleport.o fightView.o 
HitMonsterPrint.o MissMonsterPrint.o Enemy.o Smonster.o Mmonster.o Lmonster.o Cellule.o 
CelluleView.o Field.o FieldView.o ExitDoorPrint.o Game.o -o main
main.o: main.cpp
	g++ -c main.cpp
Logger.o: Logger.cpp
	g++ -c Logger.cpp
IObservable.o: IObservable.cpp
	g++ -c IObservable.cpp
Characters.o: Characters.cpp
	g++ -c Characters.cpp
Player.o: Player.cpp
	g++ -c Player.cpp
Item.o: Item.cpp
	g++ -c Item.cpp
Heal.o: Heal.cpp
	g++ -c Heal.cpp
Box.o: Box.cpp
	g++ -c Box.cpp
Teleport.o: Teleport.cpp
	g++ -c Teleport.cpp
fightView.o: fightView.cpp
	g++ -c fightView.cpp
HitMonsterPrint.o: HitMonsterPrint.cpp
	g++ -c HitMonsterPrint.cpp
MissMonsterPrint.o: MissMonsterPrint.cpp
	g++ -c MissMonsterPrint.cpp
Enemy.o: Enemy.cpp
	g++ -c Enemy.cpp
Smonster.o: Smonster.cpp
	g++ -c Smonster.cpp
Mmonster.o: Mmonster.cpp
	g++ -c Mmonster.cpp
Lmonster.o: Lmonster.cpp
	g++ -c Lmonster.cpp
Cellule.o: Cellule.cpp
	g++ -c Cellule.cpp
CelluleView.o: CelluleView.cpp
	g++ -c CelluleView.cpp
Field.o: Field.cpp
	g++ -c Field.cpp
FieldView.o: FieldView.cpp
	g++ -c FieldView.cpp
ExitDoorPrint.o: ExitDoorPrint.cpp
	g++ -c ExitDoorPrint.cpp
Game.o: Game.cpp
	g++ -c Game.cpp
clean:
	rm *.o main